project:
  type: default
  output-dir: docs
  
title: Introducing IUB Library's Open Publishing Service for Non-Traditional Documents
date: "5 June 2023"
author: Adam Mazel, Digital Publishing Librarian
institute: Scholarly Communication Department, IUB Libraries
title-slide-attributes: 
  data-notes: |-
    Who: Name, Title
    What: Introduce new library service that I'm launching: IUB Libraries' Open Publishing Service for Non-Traditional Documents
    How: Overview: What + Whom We Publish, How We Publish, and Why We Publish These Docs This Way
    Why: To publicize service

format:
  revealjs:
    scrollable: true
    overview: true
    touch: true
    progress: true
    slide-number: true
    preview-links: true
    embed-resources: true
    fig-responsive: true
    transition: slide
    css: style.css
    lang: en-US
    keywords: ["Indiana University", "Indiana University Libraries", "Open Publishing Service", "Non-Traditional Documents"]
logo: images\iu_trident_web_crimson.png
