project:
  type: default
  output-dir: docs
  
title: "Introducing \\ IUB Library's \\ Open Publishing Service \\ for Non-Traditional Documents"
date: 5 June 2023
author: 
  name: Adam Mazel, Digital Publishing Librarian
  institute: "Scholarly Communication Department, IUB Libraries"
format:
  revealjs:
    scrollable: true
    show-notes: true
    slide-number: true
    pdf-separate-fragments: true
    preview-links: true
    embed-resources: true
    transition: slide
    css: style.css
logo: images\iu_trident_web_crimson.png
