## What and Whom Do We Publish?

::: {.nonincremental}
### IU-Created:
- Bibliographies
- Books (scholarly, fiction, etc.)
- Conference Proceedings
- Digital Scholarship
- Documentation
- Manuals
- Reports
- White + Working Papers
:::

::: {.notes}
So, what is meant by "Non-Traditional Documents"?

Here are two definitions:

1) Documents created by the IU community that could benefit from being published but are inapt for scholarly or commercial presses. This is because they may be
- not apt for peer review
- too long or too short
- too esoteric
- too costly to publish or not expected to sell

2) "Non-Traditional Documents" also refers to:
 
Documents created by the IU community that would benefit from 
- low / no barriers to acceptance or publication
- fast publishing timelines
- publishing agreements that enable the author to retain copyright
:::

## How Do We Publish? Our Principles

- Diamond Open Access
- Author Retains Copyright
- Barrier-Free Publishing

::: {.notes}
Our publications are Diamond Open Access, meaning that they are published with no fees to either author or reader. 

Moreover, our authors retain copyright, so they retain ownership of their work and the right to distribute and republish the work elsewhere. 

Our publishing service is also free from publication barriers, such as peer review and return on investment. This enables us to eschew gatekeeping, publish all documents, no matter how short or long, esoteric, or limited in audience. It also enables us to publish faster than traditional presses. 
:::

## How Do We Publish? Our Services

:::: {.columns}

::: {column width="50%"}
**Services Offered Now**
- Multiformat Publishing (HTML, EPUB, PDF, Print)
- Default Design + Typesetting
- Open Access Hosting 
- Discoverability 
- Copyediting (optional)
- Print-on-Demand (optional)
- Copyright Help (optional)
- Use Metrics (optional)
:::

::: {column width="50%"}
**Services Offered Later**
- Custom Design + Typesetting
- Preservation
- Discoverability (IU Catalog)
:::

:::: {.notes}
Our publishing service is comprised of these publishing services, divided between those that are offered now and those that should be offered in the future. 

My most basic publishing service is document conversion and hosting: I take author content and convert it into three formats--default-designed and default-typeset HTML, EPUB, and PDF--using the publishing software, Quarto, which I will overview shortly.

These reformatted materials are hosted on and served open access via our Department GitHub repository, and are made discoverable via DOIs, Google Analytics, etc.

We also provide copyediting, print-on-demand, help with copyright and permissions, and use metrics and research impact upon request. 
::::

## How Do We Publish: Our Software

- Digital Publishing Platform: [Quarto](https://quarto.org/)
- [Example Schol Comm Publishing Service Publication](https://iulibscholcomm.github.io/example-publication/)

:::: {.notes}
Our digitial publication platform is Quarto.

(Show Quarto--note multimedia, data-driven publications

Show Example--note features: accessible multiformat publishing, hypothesis, text)

This slideshow is also Quarto.

Quarto is a static-site generator, meaning that it takes content in Markdown, a simplified version of HTML, and converts it into a website, or in this case a digital publication in multiple file formats, such as HTML, EPUB, and PDF. 

Quarto is Free of cost--both for use and to host--and it is Open Source, meaning that it its source code is open and available to the public for free. This makes the software trustworthy, secure, interoperable, customizable, and maintained robustly and perpetually.

:::

## Why Do We Publish These Documents This Way?

- Emerging service of academic libraries
- Unsupported need of Indiana University
- Multiformat publishing improves access and accessibility
- Affordable and Sustainable
- Improved Product

::: {.notes}
We have four main reasons for establishing this service. 

First, there is precedent for doing so: library publishing services for non-traditional documents are becoming the norm and being used considerably by authors and readers. 
Charles Watkinson, AUL for Publishing at UMichigan and Director, University of Michigan Press, has shown that "the trusted relationships formed on campus in handing [non-taditional literature] offer interesting potentials for library publishers,"

Second, while these documents are published by similar university libraries, they are not yet at IU Libraries, other than our repository being used for the most basic form of publishing, the posting and hosting of pdfs, without supporting copyediting or design.

This brings me to our third reason for establishing this service. For while pdfs are great for printing / those who prefer reading physical copies, they cannot handle dynamic or interactive media; they are hard to read on different screen sizes, from cell phones to desktops; they are not machine readable and the raw content is not accessible, unlike HTML; and they are less accessable for impaired readers than ePubs. 

In sum, single file format publishing--just posting and hosting a pdf--limits various means of access and accessibity, while multiformat publishing--publishing not only a pdf but also html and an epub, as well as raw content--broadens access and accessibility and thus potential uses and readerships. We therefore wanted to enable multiformat publishing.

We're doing so with Quarto, rather than prominent publishing platforms such as PressBooks, to advocate platforms that are affordable (free of all costs, including hosting costs), not proprietary (not subject to owner whims), and sustainable (easy to maintain, small footprint).

Lastly, offering copyediting and design help will improve the quality and appearance of the publication, furthering its success.

:::


## Wrap Up + Thank You!

- First Publication: Monograph by Curtis Lively, Distinguished Professor of Biology, IU
- Share with Constituents
- Contact: Adam Mazel, Digital Publishing Librarian, [amazel@iu.edu](mailto:amazel@iu.edu)

::: {.notes}
I'm happy to mention that we have our first client, Curtis Lively, Distinguished Professor of Biology, IU, whose monograph we are publishing.

We'd like to publicize this service. 
Is this service of interest to your constituencies? If so, please be in touch.

Thank you!

:::